version: '3.7'
services:
  redis:
    container_name: redis
    image: redis:5.0.5
    ports:
      - 6379:6379
    command: >
      bash -c "mkdir -p /var/log/redis && 
      touch /var/log/redis/redis.log && 
      redis-server --logfile /var/log/redis/redis.log"
    volumes:
      - ./log:/var/log/redis