version: '3.7'
services:
  redis:
    container_name: redis
    hostname: redis
    image: redis:5.0.7
    restart: always
    ports:
      - 6379:6379

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:redis-commander-210
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - 8081:8081
