version: "3.7"
services:
  mariadb:
    container_name: mariadb
    image: mariadb:10.4.7
    volumes:
      - ./conf:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: test
    ports:
      - 3306:3306