version: "3.7"
services:
    node-1:
        image: mariadb-galera:10.4.12
        container_name: node-1
        ports:
          - 4001:3306
        command: mysqld --wsrep-new-cluster

    node-2:
        image: mariadb-galera:10.4.12
        container_name: node-2
        links:
          - node-1
        ports:
          - 4002:3306
        command: mysqld

    node-3:
        image: mariadb-galera:10.4.12
        container_name: node-3
        links:
          - node-1
        ports:
          - 4003:3306
        command: mysqld

    maxscale:
        image: mariadb/maxscale:2.4.2
        container_name: maxscale
        depends_on:
            - node-1
            - node-2
            - node-3
        volumes:
            - ./maxscale.cnf.d:/etc/maxscale.cnf.d
        ports:
            - 4006:4006  # readwrite port
            - 4008:4008  # readonly port
            - 8989:8989  # REST API port